### ISSUE TITLE
Create a `Media` Prisma model

### ISSUE THREAD

**Issue by reanimatedmanx** [reanimatedmanx/crunchytest#6]
# Overview

Create a `Media` prisma model with the following fields

```yaml
id: number
title: string
type: string
genre: string
releaseYear: number
rating: number # (1-10)
```
